### ISSUE TITLE
Process Management using systemd

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/agent#2]
One of the core components of the Agent will be to manage processes.
We decided to use systemd as the tool doing the actual supervision as it's available on all our target systems (Debian, Ubuntu, RHEL).

The Agent needs a way to manager systemd Units and this ticket is about implementing this functionality.

Every time a process starts it'll need configuration data on disk which needs to be materialized from configuration in the Operator/Orchestrator resources.
To make debugging easier we'd like to have a new uniquely named directory in a configurable location (e.g. /var/run/stackable/...) which has all the files a process needs.
An open question is whether restarts due to failure reuse  an existing configuration directory or not.

This is the epic for this task and these are the dependencies:

- [ ] #3 Create a data structure (object/resource) to describe a systemd unit
- [ ] #4 Investigate existing crates that deal with systemd and see if we can use one or more of these for the functionatily we need
- [ ] #8 Investigate whether we can put our unit files in a separate location from the standard unit files
- [ ] #5 Create systemd unit files
- [ ] #6 Update systemd unit files
- [ ] #7 Delete systemd unit files
- [ ] #9 Reload systemd (daemon-reload)
- [ ] #10 Receive and process notifications from systemd about process state changes (e.g. a process dying or restarting) - this will probably happen via D-Bus
- [ ] #11 Trigger a start/stop/restart of a unit
- [ ] #12 Materialize the required configuration files/data, keytabs, certificates etc.

Open Issues/questions:
* Log file target (stdout/stderr)
* Restart/failure behavior
* Environment variable
* Start on boot behavior
